// SPDX-License-Identifier: MIT OR Apache-2.0
//
// @generated by tools/rpc-scrape/rpc_scrape.py — DO NOT EDIT BY HAND.
//
// Upstream: octra-labs/lite_node (BSD-3-Clause)
// SOURCE_COMMIT: dd342e754c91df55a41b515c510369d637af2385
//
// This is the REAL JSON-RPC surface of the Octra lite node, derived from
// its OCaml dispatch tables. The mock uses it to guarantee it can never
// answer a method the chain does not have, and never invent an error
// shape the chain does not emit.
//
// Regenerate with:
//   python3 tools/rpc-scrape/rpc_scrape.py \
//       --upstream <lite_node checkout> \
//       --out crates/octra-mock-rpc/src/methods.rs

/// The upstream commit these tables were scraped from. Must match
/// `docker/octra-node/Dockerfile`'s `SOURCE_COMMIT`.
pub const SOURCE_COMMIT: &str = "dd342e754c91df55a41b515c510369d637af2385";

/// JSON-RPC / chain error codes, scraped from `lib/core/rpc.ml`.
///
/// Codes are the node's, verbatim. Where the node's message is a
/// template, the Rust side gets a formatter below instead of a const.
pub mod codes {
    /// node: `parse_error` -> parse error
    pub const PARSE_ERROR: i32 = -32700;
    /// node: `invalid_params` -> invalid params
    pub const INVALID_PARAMS: i32 = -32602;
    /// node: `method_not_found` -> method not found: %s
    pub const METHOD_NOT_FOUND: i32 = -32601;
    /// node: `invalid_request` -> invalid request
    pub const INVALID_REQUEST: i32 = -32600;
    /// node: `sender_not_found` -> sender not found
    pub const SENDER_NOT_FOUND: i32 = 100;
    /// node: `invalid_signature` -> invalid signature
    pub const INVALID_SIGNATURE: i32 = 101;
    /// node: `invalid_nonce` -> invalid nonce
    pub const INVALID_NONCE: i32 = 102;
    /// node: `nonce_too_far` -> nonce too far ahead
    pub const NONCE_TOO_FAR: i32 = 103;
    /// node: `insufficient_balance` -> insufficient balance
    pub const INSUFFICIENT_BALANCE: i32 = 104;
    /// node: `malformed_tx` -> malformed transaction
    pub const MALFORMED_TX: i32 = 105;
    /// node: `duplicate_tx` -> duplicate transaction
    pub const DUPLICATE_TX: i32 = 106;
    /// node: `staging_full` -> staging full
    pub const STAGING_FULL: i32 = 107;
    /// node: `self_transfer` -> self transfer
    pub const SELF_TRANSFER: i32 = 108;
    /// node: `invalid_address` -> invalid address
    pub const INVALID_ADDRESS: i32 = 109;
    /// node: `service_unavailable` -> service unavailable
    pub const SERVICE_UNAVAILABLE: i32 = 110;
    /// node: `supply_violation` -> supply violation
    pub const SUPPLY_VIOLATION: i32 = 111;
    /// node: `not_found` -> not found
    pub const NOT_FOUND: i32 = 112;
    /// node: `fee_too_low` -> fee too low
    pub const FEE_TOO_LOW: i32 = 113;
    /// node: `tx_too_large` -> transaction too large
    pub const TX_TOO_LARGE: i32 = 114;
    /// node: `self_only_op` -> invalid operation target
    pub const SELF_ONLY_OP: i32 = 115;
}

/// Message text the node pairs with each code (template markers intact).
pub const ERROR_MESSAGES: &[(i32, &str)] = &[
    (-32700, "parse error"),
    (-32602, "invalid params"),
    (-32601, "method not found: %s"),
    (-32600, "invalid request"),
    (100, "sender not found"),
    (101, "invalid signature"),
    (102, "invalid nonce"),
    (103, "nonce too far ahead"),
    (104, "insufficient balance"),
    (105, "malformed transaction"),
    (106, "duplicate transaction"),
    (107, "staging full"),
    (108, "self transfer"),
    (109, "invalid address"),
    (110, "service unavailable"),
    (111, "supply violation"),
    (112, "not found"),
    (113, "fee too low"),
    (114, "transaction too large"),
    (115, "invalid operation target"),
];

/// The node's method-not-found error, byte-for-byte.
///
/// `lib/core/rpc.ml`: `method_not_found m = { code = -32601; message =
/// Printf.sprintf "method not found: %s" m; data = None }` — note there is
/// NO `data` member, so the serialized error object is exactly
/// `{"code":-32601,"message":"method not found: <m>"}`.
pub const METHOD_NOT_FOUND_CODE: i32 = -32601;

#[must_use]
pub fn method_not_found_message(method: &str) -> String {
    format!("method not found: {method}")
}

/// Every dispatchable method name on the node (212 unique,
/// 212 route entries including aliases), sorted.
///
/// Sourced from `node_rpc_server.ml::dispatch`, which concatenates:
///   - Status_read_rpc.core_dispatch
///   - Account_read_rpc.public_dispatch
///   - history_dispatch
///   - rest_dispatch
///   - circle_dispatch
///   - program_dispatch
///   - Account_read_rpc.pvac_dispatch
///   - Status_read_rpc.proof_dispatch
///   - effect_dispatch.submission
///   - effect_dispatch.staging
///   - effect_dispatch.mutation
///   - compute_dispatch
pub const NODE_METHODS: &[&str] = &[
    "circle_asset",
    "circle_asset_ciphertext",
    "circle_asset_ciphertext_auth",
    "circle_asset_ciphertext_by_resource_key",
    "circle_asset_ciphertext_by_resource_key_auth",
    "circle_asset_ciphertext_by_slot_ref",
    "circle_asset_ciphertext_by_slot_ref_auth",
    "circle_asset_ciphertext_by_state_ref",
    "circle_asset_ciphertext_by_state_ref_auth",
    "circle_balance_binding",
    "circle_balance_binding_auth",
    "circle_balance_cell",
    "circle_balance_cell_auth",
    "circle_balance_workflow",
    "circle_balance_workflow_auth",
    "circle_hfhe_policy",
    "circle_hfhe_policy_auth",
    "circle_info",
    "circle_info_auth",
    "circle_ingress_packet",
    "circle_ingress_packet_auth",
    "circle_key_policy",
    "circle_key_policy_auth",
    "circle_object_detail",
    "circle_object_detail_auth",
    "circle_object_list",
    "circle_object_list_auth",
    "circle_object_member",
    "circle_object_member_auth",
    "circle_object_members",
    "circle_object_members_auth",
    "circle_object_refs",
    "circle_object_refs_auth",
    "circle_object_summary",
    "circle_object_summary_auth",
    "circle_outbox_claim",
    "circle_outbox_claim_auth",
    "circle_outbox_intent",
    "circle_outbox_intent_auth",
    "circle_outbox_status",
    "circle_outbox_status_auth",
    "circle_program_auth",
    "circle_program_info",
    "circle_program_info_auth",
    "circle_register_binding",
    "circle_register_binding_auth",
    "circle_register_cell",
    "circle_register_cell_auth",
    "circle_register_workflow",
    "circle_register_workflow_auth",
    "circle_slot_policy",
    "circle_slot_policy_auth",
    "circle_state_descriptor",
    "circle_state_descriptor_auth",
    "circle_state_policy",
    "circle_state_policy_auth",
    "circle_storage",
    "circle_storage_auth",
    "circle_storage_dump",
    "circle_storage_dump_auth",
    "circle_transport_policy",
    "circle_transport_policy_auth",
    "circle_view",
    "circle_view_auth",
    "contract_call",
    "contract_receipt",
    "contract_saveAbi",
    "contract_source",
    "contract_verify",
    "epoch_current",
    "epoch_get",
    "epoch_list",
    "epoch_summaries",
    "node_metrics",
    "node_stats",
    "node_status",
    "node_version",
    "octra_account",
    "octra_accountProof",
    "octra_balance",
    "octra_circleAsset",
    "octra_circleAssetCiphertext",
    "octra_circleAssetCiphertextAuth",
    "octra_circleAssetCiphertextByResourceKey",
    "octra_circleAssetCiphertextByResourceKeyAuth",
    "octra_circleAssetCiphertextBySlotRef",
    "octra_circleAssetCiphertextBySlotRefAuth",
    "octra_circleAssetCiphertextByStateRef",
    "octra_circleAssetCiphertextByStateRefAuth",
    "octra_circleBalanceBinding",
    "octra_circleBalanceBindingAuth",
    "octra_circleBalanceCell",
    "octra_circleBalanceCellAuth",
    "octra_circleBalanceWorkflow",
    "octra_circleBalanceWorkflowAuth",
    "octra_circleComputeCancel",
    "octra_circleComputeStatus",
    "octra_circleComputeSubmit",
    "octra_circleHfhePolicy",
    "octra_circleHfhePolicyAuth",
    "octra_circleInfo",
    "octra_circleInfoAuth",
    "octra_circleIngressPacket",
    "octra_circleIngressPacketAuth",
    "octra_circleKeyPolicy",
    "octra_circleKeyPolicyAuth",
    "octra_circleObjectDetail",
    "octra_circleObjectDetailAuth",
    "octra_circleObjectList",
    "octra_circleObjectListAuth",
    "octra_circleObjectMember",
    "octra_circleObjectMemberAuth",
    "octra_circleObjectMembers",
    "octra_circleObjectMembersAuth",
    "octra_circleObjectRefs",
    "octra_circleObjectRefsAuth",
    "octra_circleObjectSummary",
    "octra_circleObjectSummaryAuth",
    "octra_circleOutboxClaim",
    "octra_circleOutboxClaimAuth",
    "octra_circleOutboxIntent",
    "octra_circleOutboxIntentAuth",
    "octra_circleOutboxStatus",
    "octra_circleOutboxStatusAuth",
    "octra_circleProgram",
    "octra_circleProgramAuth",
    "octra_circleProgramInfo",
    "octra_circleProgramInfoAuth",
    "octra_circleRegisterBinding",
    "octra_circleRegisterBindingAuth",
    "octra_circleRegisterCell",
    "octra_circleRegisterCellAuth",
    "octra_circleRegisterWorkflow",
    "octra_circleRegisterWorkflowAuth",
    "octra_circleSlotPolicy",
    "octra_circleSlotPolicyAuth",
    "octra_circleStateDescriptor",
    "octra_circleStateDescriptorAuth",
    "octra_circleStatePolicy",
    "octra_circleStatePolicyAuth",
    "octra_circleStorage",
    "octra_circleStorageAuth",
    "octra_circleStorageDump",
    "octra_circleStorageDumpAuth",
    "octra_circleTransportPolicy",
    "octra_circleTransportPolicyAuth",
    "octra_circleView",
    "octra_circleViewAuth",
    "octra_compileAml",
    "octra_compileAmlMulti",
    "octra_compileAssembly",
    "octra_computeContractAddress",
    "octra_computeProgramAddress",
    "octra_consensusPeerStates",
    "octra_contractAbi",
    "octra_contractBytecode",
    "octra_contractStorage",
    "octra_contractStorageDump",
    "octra_encryptedBalance",
    "octra_encryptedCipher",
    "octra_epochProof",
    "octra_epochTags",
    "octra_listContracts",
    "octra_listPrograms",
    "octra_nonce",
    "octra_privateTransfer",
    "octra_programAbi",
    "octra_programBytecode",
    "octra_programCall",
    "octra_programInfo",
    "octra_programReceipt",
    "octra_programSaveAbi",
    "octra_programSource",
    "octra_programStorage",
    "octra_programStorageDump",
    "octra_programVerify",
    "octra_publicKey",
    "octra_pvacMigrationStatus",
    "octra_pvacPubkey",
    "octra_pvacStatus",
    "octra_recentTransactions",
    "octra_recommendedFee",
    "octra_registerPublicKey",
    "octra_registerPvacPubkey",
    "octra_rejectedByAddress",
    "octra_roundWitness",
    "octra_runtimeVersion",
    "octra_search",
    "octra_signedRoot",
    "octra_stealthOutputs",
    "octra_stealthOutputsById",
    "octra_stealthOutputsPage",
    "octra_submit",
    "octra_submitBatch",
    "octra_supply",
    "octra_tokenTransfersByAddress",
    "octra_tokensByAddress",
    "octra_totalTransactions",
    "octra_transaction",
    "octra_transactions",
    "octra_transactionsByAddress",
    "octra_transactionsByEpoch",
    "octra_txInclusionProof",
    "octra_validateAddress",
    "octra_validatorSetProof",
    "octra_validatorViewPubkey",
    "octra_viewPubkey",
    "staging_estimateOu",
    "staging_remove",
    "staging_stats",
    "staging_view",
    "vm_contract",
];

/// `(alias, primary)` pairs — upstream `route_aliases` registers BOTH
/// names against the same handler, so both are live.
pub const NODE_METHOD_ALIASES: &[(&str, &str)] = &[
    ("octra_circleAsset", "circle_asset"),
    ("octra_circleAssetCiphertext", "circle_asset_ciphertext"),
    (
        "octra_circleAssetCiphertextAuth",
        "circle_asset_ciphertext_auth",
    ),
    (
        "octra_circleAssetCiphertextByResourceKey",
        "circle_asset_ciphertext_by_resource_key",
    ),
    (
        "octra_circleAssetCiphertextByResourceKeyAuth",
        "circle_asset_ciphertext_by_resource_key_auth",
    ),
    (
        "octra_circleAssetCiphertextBySlotRef",
        "circle_asset_ciphertext_by_slot_ref",
    ),
    (
        "octra_circleAssetCiphertextBySlotRefAuth",
        "circle_asset_ciphertext_by_slot_ref_auth",
    ),
    (
        "octra_circleAssetCiphertextByStateRef",
        "circle_asset_ciphertext_by_state_ref",
    ),
    (
        "octra_circleAssetCiphertextByStateRefAuth",
        "circle_asset_ciphertext_by_state_ref_auth",
    ),
    ("octra_circleBalanceBinding", "circle_balance_binding"),
    (
        "octra_circleBalanceBindingAuth",
        "circle_balance_binding_auth",
    ),
    ("octra_circleBalanceCell", "circle_balance_cell"),
    ("octra_circleBalanceCellAuth", "circle_balance_cell_auth"),
    ("octra_circleBalanceWorkflow", "circle_balance_workflow"),
    (
        "octra_circleBalanceWorkflowAuth",
        "circle_balance_workflow_auth",
    ),
    ("octra_circleHfhePolicy", "circle_hfhe_policy"),
    ("octra_circleHfhePolicyAuth", "circle_hfhe_policy_auth"),
    ("octra_circleInfo", "circle_info"),
    ("octra_circleInfoAuth", "circle_info_auth"),
    ("octra_circleIngressPacket", "circle_ingress_packet"),
    (
        "octra_circleIngressPacketAuth",
        "circle_ingress_packet_auth",
    ),
    ("octra_circleKeyPolicy", "circle_key_policy"),
    ("octra_circleKeyPolicyAuth", "circle_key_policy_auth"),
    ("octra_circleObjectDetail", "circle_object_detail"),
    ("octra_circleObjectDetailAuth", "circle_object_detail_auth"),
    ("octra_circleObjectList", "circle_object_list"),
    ("octra_circleObjectListAuth", "circle_object_list_auth"),
    ("octra_circleObjectMember", "circle_object_member"),
    ("octra_circleObjectMemberAuth", "circle_object_member_auth"),
    ("octra_circleObjectMembers", "circle_object_members"),
    (
        "octra_circleObjectMembersAuth",
        "circle_object_members_auth",
    ),
    ("octra_circleObjectRefs", "circle_object_refs"),
    ("octra_circleObjectRefsAuth", "circle_object_refs_auth"),
    ("octra_circleObjectSummary", "circle_object_summary"),
    (
        "octra_circleObjectSummaryAuth",
        "circle_object_summary_auth",
    ),
    ("octra_circleOutboxClaim", "circle_outbox_claim"),
    ("octra_circleOutboxClaimAuth", "circle_outbox_claim_auth"),
    ("octra_circleOutboxIntent", "circle_outbox_intent"),
    ("octra_circleOutboxIntentAuth", "circle_outbox_intent_auth"),
    ("octra_circleOutboxStatus", "circle_outbox_status"),
    ("octra_circleOutboxStatusAuth", "circle_outbox_status_auth"),
    ("octra_circleProgramAuth", "circle_program_auth"),
    ("octra_circleProgramInfo", "circle_program_info"),
    ("octra_circleProgramInfoAuth", "circle_program_info_auth"),
    ("octra_circleRegisterBinding", "circle_register_binding"),
    (
        "octra_circleRegisterBindingAuth",
        "circle_register_binding_auth",
    ),
    ("octra_circleRegisterCell", "circle_register_cell"),
    ("octra_circleRegisterCellAuth", "circle_register_cell_auth"),
    ("octra_circleRegisterWorkflow", "circle_register_workflow"),
    (
        "octra_circleRegisterWorkflowAuth",
        "circle_register_workflow_auth",
    ),
    ("octra_circleSlotPolicy", "circle_slot_policy"),
    ("octra_circleSlotPolicyAuth", "circle_slot_policy_auth"),
    ("octra_circleStateDescriptor", "circle_state_descriptor"),
    (
        "octra_circleStateDescriptorAuth",
        "circle_state_descriptor_auth",
    ),
    ("octra_circleStatePolicy", "circle_state_policy"),
    ("octra_circleStatePolicyAuth", "circle_state_policy_auth"),
    ("octra_circleStorage", "circle_storage"),
    ("octra_circleStorageAuth", "circle_storage_auth"),
    ("octra_circleStorageDump", "circle_storage_dump"),
    ("octra_circleStorageDumpAuth", "circle_storage_dump_auth"),
    ("octra_circleTransportPolicy", "circle_transport_policy"),
    (
        "octra_circleTransportPolicyAuth",
        "circle_transport_policy_auth",
    ),
    ("octra_circleView", "circle_view"),
    ("octra_circleViewAuth", "circle_view_auth"),
    (
        "octra_computeProgramAddress",
        "octra_computeContractAddress",
    ),
    ("octra_listPrograms", "octra_listContracts"),
    ("octra_programAbi", "octra_contractAbi"),
    ("octra_programBytecode", "octra_contractBytecode"),
    ("octra_programCall", "contract_call"),
    ("octra_programInfo", "vm_contract"),
    ("octra_programReceipt", "contract_receipt"),
    ("octra_programSaveAbi", "contract_saveAbi"),
    ("octra_programSource", "contract_source"),
    ("octra_programStorage", "octra_contractStorage"),
    ("octra_programStorageDump", "octra_contractStorageDump"),
    ("octra_programVerify", "contract_verify"),
];

/// Methods grouped by the upstream route table they come from.
pub const NODE_METHOD_GROUPS: &[(&str, &[&str])] = &[
    // node_runtime/rpc_dispatch.ml::circle_routes
    (
        "circle",
        &[
            "circle_asset",
            "circle_asset_ciphertext",
            "circle_asset_ciphertext_auth",
            "circle_asset_ciphertext_by_resource_key",
            "circle_asset_ciphertext_by_resource_key_auth",
            "circle_asset_ciphertext_by_slot_ref",
            "circle_asset_ciphertext_by_slot_ref_auth",
            "circle_asset_ciphertext_by_state_ref",
            "circle_asset_ciphertext_by_state_ref_auth",
            "circle_balance_binding",
            "circle_balance_binding_auth",
            "circle_balance_cell",
            "circle_balance_cell_auth",
            "circle_balance_workflow",
            "circle_balance_workflow_auth",
            "circle_hfhe_policy",
            "circle_hfhe_policy_auth",
            "circle_info",
            "circle_info_auth",
            "circle_ingress_packet",
            "circle_ingress_packet_auth",
            "circle_key_policy",
            "circle_key_policy_auth",
            "circle_object_detail",
            "circle_object_detail_auth",
            "circle_object_list",
            "circle_object_list_auth",
            "circle_object_member",
            "circle_object_member_auth",
            "circle_object_members",
            "circle_object_members_auth",
            "circle_object_refs",
            "circle_object_refs_auth",
            "circle_object_summary",
            "circle_object_summary_auth",
            "circle_outbox_claim",
            "circle_outbox_claim_auth",
            "circle_outbox_intent",
            "circle_outbox_intent_auth",
            "circle_outbox_status",
            "circle_outbox_status_auth",
            "circle_program_auth",
            "circle_program_info",
            "circle_program_info_auth",
            "circle_register_binding",
            "circle_register_binding_auth",
            "circle_register_cell",
            "circle_register_cell_auth",
            "circle_register_workflow",
            "circle_register_workflow_auth",
            "circle_slot_policy",
            "circle_slot_policy_auth",
            "circle_state_descriptor",
            "circle_state_descriptor_auth",
            "circle_state_policy",
            "circle_state_policy_auth",
            "circle_storage",
            "circle_storage_auth",
            "circle_storage_dump",
            "circle_storage_dump_auth",
            "circle_transport_policy",
            "circle_transport_policy_auth",
            "circle_view",
            "circle_view_auth",
            "octra_circleAsset",
            "octra_circleAssetCiphertext",
            "octra_circleAssetCiphertextAuth",
            "octra_circleAssetCiphertextByResourceKey",
            "octra_circleAssetCiphertextByResourceKeyAuth",
            "octra_circleAssetCiphertextBySlotRef",
            "octra_circleAssetCiphertextBySlotRefAuth",
            "octra_circleAssetCiphertextByStateRef",
            "octra_circleAssetCiphertextByStateRefAuth",
            "octra_circleBalanceBinding",
            "octra_circleBalanceBindingAuth",
            "octra_circleBalanceCell",
            "octra_circleBalanceCellAuth",
            "octra_circleBalanceWorkflow",
            "octra_circleBalanceWorkflowAuth",
            "octra_circleHfhePolicy",
            "octra_circleHfhePolicyAuth",
            "octra_circleInfo",
            "octra_circleInfoAuth",
            "octra_circleIngressPacket",
            "octra_circleIngressPacketAuth",
            "octra_circleKeyPolicy",
            "octra_circleKeyPolicyAuth",
            "octra_circleObjectDetail",
            "octra_circleObjectDetailAuth",
            "octra_circleObjectList",
            "octra_circleObjectListAuth",
            "octra_circleObjectMember",
            "octra_circleObjectMemberAuth",
            "octra_circleObjectMembers",
            "octra_circleObjectMembersAuth",
            "octra_circleObjectRefs",
            "octra_circleObjectRefsAuth",
            "octra_circleObjectSummary",
            "octra_circleObjectSummaryAuth",
            "octra_circleOutboxClaim",
            "octra_circleOutboxClaimAuth",
            "octra_circleOutboxIntent",
            "octra_circleOutboxIntentAuth",
            "octra_circleOutboxStatus",
            "octra_circleOutboxStatusAuth",
            "octra_circleProgram",
            "octra_circleProgramAuth",
            "octra_circleProgramInfo",
            "octra_circleProgramInfoAuth",
            "octra_circleRegisterBinding",
            "octra_circleRegisterBindingAuth",
            "octra_circleRegisterCell",
            "octra_circleRegisterCellAuth",
            "octra_circleRegisterWorkflow",
            "octra_circleRegisterWorkflowAuth",
            "octra_circleSlotPolicy",
            "octra_circleSlotPolicyAuth",
            "octra_circleStateDescriptor",
            "octra_circleStateDescriptorAuth",
            "octra_circleStatePolicy",
            "octra_circleStatePolicyAuth",
            "octra_circleStorage",
            "octra_circleStorageAuth",
            "octra_circleStorageDump",
            "octra_circleStorageDumpAuth",
            "octra_circleTransportPolicy",
            "octra_circleTransportPolicyAuth",
            "octra_circleView",
            "octra_circleViewAuth",
        ],
    ),
    // node_runtime/rpc_dispatch.ml::program_routes
    (
        "program",
        &[
            "contract_call",
            "contract_receipt",
            "contract_saveAbi",
            "contract_source",
            "contract_verify",
            "octra_compileAml",
            "octra_compileAmlMulti",
            "octra_compileAssembly",
            "octra_computeContractAddress",
            "octra_computeProgramAddress",
            "octra_contractAbi",
            "octra_contractBytecode",
            "octra_contractStorage",
            "octra_contractStorageDump",
            "octra_listContracts",
            "octra_listPrograms",
            "octra_programAbi",
            "octra_programBytecode",
            "octra_programCall",
            "octra_programInfo",
            "octra_programReceipt",
            "octra_programSaveAbi",
            "octra_programSource",
            "octra_programStorage",
            "octra_programStorageDump",
            "octra_programVerify",
            "octra_tokensByAddress",
            "vm_contract",
        ],
    ),
    // node_runtime/rpc_effect_dispatch.ml::dispatch
    (
        "effect",
        &[
            "octra_privateTransfer",
            "octra_registerPublicKey",
            "octra_registerPvacPubkey",
            "octra_submit",
            "octra_submitBatch",
            "staging_remove",
        ],
    ),
    // node_runtime/status_read_rpc.ml::core_dispatch
    (
        "status_core",
        &[
            "node_metrics",
            "node_stats",
            "node_status",
            "node_version",
            "octra_runtimeVersion",
        ],
    ),
    // node_runtime/status_read_rpc.ml::proof_dispatch
    (
        "status_proof",
        &[
            "octra_accountProof",
            "octra_consensusPeerStates",
            "octra_epochProof",
            "octra_epochTags",
            "octra_roundWitness",
            "octra_signedRoot",
            "octra_txInclusionProof",
            "octra_validatorSetProof",
            "octra_validatorViewPubkey",
        ],
    ),
    // node_runtime/account_read_rpc.ml::public_dispatch
    (
        "account_public",
        &[
            "octra_account",
            "octra_balance",
            "octra_nonce",
            "octra_publicKey",
            "octra_supply",
            "octra_totalTransactions",
            "octra_validateAddress",
        ],
    ),
    // node_runtime/account_read_rpc.ml::pvac_dispatch
    (
        "account_pvac",
        &[
            "octra_encryptedBalance",
            "octra_encryptedCipher",
            "octra_pvacMigrationStatus",
            "octra_pvacPubkey",
            "octra_pvacStatus",
            "octra_stealthOutputs",
            "octra_stealthOutputsById",
            "octra_stealthOutputsPage",
            "octra_viewPubkey",
        ],
    ),
    // node_runtime/history_read_rpc.ml::dispatch
    (
        "history",
        &[
            "octra_recentTransactions",
            "octra_rejectedByAddress",
            "octra_tokenTransfersByAddress",
            "octra_transaction",
            "octra_transactions",
            "octra_transactionsByAddress",
            "octra_transactionsByEpoch",
        ],
    ),
    // node_runtime/rest_read_rpc.ml::dispatch
    (
        "rest",
        &[
            "epoch_current",
            "epoch_get",
            "epoch_list",
            "epoch_summaries",
            "octra_recommendedFee",
            "octra_search",
            "staging_estimateOu",
            "staging_stats",
            "staging_view",
        ],
    ),
    // node_runtime/node_rpc_server.ml::compute_dispatch
    (
        "compute",
        &[
            "octra_circleComputeCancel",
            "octra_circleComputeStatus",
            "octra_circleComputeSubmit",
        ],
    ),
];

/// Is `method` a method the real node dispatches?
///
/// The mock MUST consult this before answering anything, so that a method
/// the chain lacks can never be silently invented in a test.
#[must_use]
pub fn is_node_method(method: &str) -> bool {
    NODE_METHODS.binary_search(&method).is_ok()
}

/// Resolve an alias to its primary name (identity for primaries).
#[must_use]
pub fn primary_name(method: &str) -> &str {
    NODE_METHOD_ALIASES
        .iter()
        .find(|(alias, _)| *alias == method)
        .map_or(method, |(_, primary)| *primary)
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn methods_are_sorted_and_unique() {
        // `is_node_method` binary-searches; a regeneration that broke the
        // ordering would make lookups silently wrong.
        for pair in NODE_METHODS.windows(2) {
            assert!(pair[0] < pair[1], "NODE_METHODS unsorted at {pair:?}");
        }
    }

    #[test]
    fn plausible_method_count() {
        assert_eq!(NODE_METHODS.len(), 212);
        assert_eq!(NODE_METHOD_ALIASES.len(), 76);
    }

    #[test]
    fn aliases_and_primaries_are_both_live() {
        for (alias, primary) in NODE_METHOD_ALIASES {
            assert!(is_node_method(alias), "alias {alias} missing");
            assert!(is_node_method(primary), "primary {primary} missing");
            assert_eq!(primary_name(alias), *primary);
        }
    }

    #[test]
    fn fiction_is_absent() {
        // These were in octra-mock-rpc and exist NOWHERE in the node.
        // Zero grep hits in lite_node @ SOURCE_COMMIT.
        for fake in [
            "octra_isValidator",
            "octra_fheLoadPk",
            "octra_fheEncrypt",
            "octra_fheAdd",
            "octra_fheAddConst",
            "octra_fheVerifyZero",
            "octra_fheDecrypt",
            "octra_fheMakeZeroProof",
        ] {
            assert!(!is_node_method(fake), "{fake} is not a real node method");
        }
    }

    #[test]
    fn method_not_found_matches_the_node() {
        assert_eq!(METHOD_NOT_FOUND_CODE, -32601);
        assert_eq!(
            method_not_found_message("octra_isValidator"),
            "method not found: octra_isValidator"
        );
    }
}
